<?php

class Kantone
{
    public $kantone = array (
        0 =>
            array (
                'Kuerzel' => 'ZH',
                'Kanton' => 'Zürich',
                'Standesstimme' => '1',
                'Beitritt' => 1351,
                'Hauptort' => 'Zürich',
                'Einwohner' => '1392396',
                'Auslaender' => '24,9 %',
                'Flaeche' => '1729',
                'Dichte' => '805',
                'Gemeinden' => 171,
                'Amtssprache' => 'deutsch',
            ),
        1 =>
            array (
                'Kuerzel' => 'BE',
                'Kanton' => 'Bern',
                'Standesstimme' => '1',
                'Beitritt' => 1353,
                'Hauptort' => 'Bern',
                'Einwohner' => '985046',
                'Auslaender' => '13,7 %',
                'Flaeche' => '5959',
                'Dichte' => '165',
                'Gemeinden' => 382,
                'Amtssprache' => 'deutsch, französisch',
            ),
        2 =>
            array (
                'Kuerzel' => 'LU',
                'Kanton' => 'Luzern ',
                'Standesstimme' => '1',
                'Beitritt' => 1332,
                'Hauptort' => 'Luzern',
                'Einwohner 1' => '381966',
                'Auslaender 2' => '16,8 %',
                'Flaeche 3' => '1493',
                'Dichte 4' => '256',
                'Gemeinden 6' => 87,
                'Amtssprache' => 'deutsch',
            ),
        3 =>
            array (
                'Kuerzel' => 'UR',
                'Kanton' => 'Uri ',
                'Standesstimme' => '1',
                'Beitritt' => 1291,
                'Hauptort' => 'Altdorf',
                'Einwohner' => '35382',
                'Auslaender' => '10,6 %',
                'Flaeche' => '1077',
                'Dichte' => '33',
                'Gemeinden' => 20,
                'Amtssprache' => 'deutsch',
            ),
        4 =>
            array (
                'Kuerzel' => 'SZ',
                'Kanton' => 'Schwyz ',
                'Standesstimme' => '1',
                'Beitritt' => 1291,
                'Hauptort' => 'Schwyz',
                'Einwohner' => '147904',
                'Auslaender' => '19,3 %',
                'Flaeche' => '908',
                'Dichte' => '163',
                'Gemeinden' => 30,
                'Amtssprache' => 'deutsch',
            ),
        5 =>
            array (
                'Kuerzel' => 'OW',
                'Kanton' => 'Obwalden',
                'Standesstimme' => '0,5',
                'Beitritt' => 1291,
                'Hauptort' => 'Sarnen',
                'Einwohner' => '35878',
                'Auslaender' => '13,8 %',
                'Flaeche' => '491',
                'Dichte' => '73',
                'Gemeinden' => 7,
                'Amtssprache' => 'deutsch',
            ),
        6 =>
            array (
                'Kuerzel' => 'NW',
                'Kanton' => 'Nidwalden ',
                'Standesstimme' => '0,5',
                'Beitritt' => 1291,
                'Hauptort' => 'Stans',
                'Einwohner' => '41311',
                'Auslaender' => '12,4 %',
                'Flaeche' => '276',
                'Dichte' => '150',
                'Gemeinden' => 11,
                'Amtssprache' => 'deutsch',
            ),
        7 =>
            array (
                'Kuerzel' => 'GL',
                'Kanton' => 'Glarus ',
                'Standesstimme' => '1',
                'Beitritt' => 1352,
                'Hauptort' => 'Glarus',
                'Einwohner' => '39217',
                'Auslaender' => '21,6 %',
                'Flaeche' => '685',
                'Dichte' => '57',
                'Gemeinden' => 3,
                'Amtssprache' => 'deutsch',
            ),
        8 =>
            array (
                'Kuerzel' => 'ZG',
                'Kanton' => 'Zug ',
                'Standesstimme' => '1',
                'Beitritt' => 1352,
                'Hauptort' => 'Zug',
                'Einwohner' => '115104',
                'Auslaender' => '25,5 %',
                'Flaeche' => '239',
                'Dichte' => '482',
                'Gemeinden' => 11,
                'Amtssprache' => 'deutsch',
            ),
        9 =>
            array (
                'Kuerzel' => 'FR',
                'Kanton' => 'Freiburg ',
                'Standesstimme' => '1',
                'Beitritt' => 1481,
                'Hauptort' => 'Freiburg',
                'Einwohner' => '284668',
                'Auslaender' => '20,5 %',
                'Flaeche' => '1671',
                'Dichte' => '170',
                'Gemeinden' => 165,
                'Amtssprache' => 'französisch, deutsch',
            ),
        10 =>
            array (
                'Kuerzel' => 'SO',
                'Kanton' => 'Solothurn ',
                'Standesstimme' => '1',
                'Beitritt' => 1481,
                'Hauptort' => 'Solothurn',
                'Einwohner' => '257393',
                'Auslaender' => '20,0 %',
                'Flaeche' => '791',
                'Dichte' => '325',
                'Gemeinden' => 120,
                'Amtssprache' => 'deutsch',
            ),
        11 =>
            array (
                'Kuerzel' => 'BS',
                'Kanton' => 'Basel-Stadt ',
                'Standesstimme' => '0,5',
                'Beitritt' => 1501,
                'Hauptort' => 'Basel',
                'Einwohner' => '194661',
                'Auslaender' => '34,1 %',
                'Flaeche' => '37',
                'Dichte' => '5034',
                'Gemeinden' => 3,
                'Amtssprache' => 'deutsch',
            ),
        12 =>
            array (
                'Kuerzel' => 'BL',
                'Kanton' => 'Basel-Landschaft',
                'Standesstimme' => '0,5',
                'Beitritt' => 1501,
                'Hauptort' => 'Liestal',
                'Einwohner' => '277614',
                'Auslaender' => '19,9 %',
                'Flaeche' => '518',
                'Dichte' => '532',
                'Gemeinden' => 86,
                'Amtssprache' => 'deutsch',
            ),
        13 =>
            array (
                'Kuerzel' => 'SH',
                'Kanton' => 'Schaffhausen ',
                'Standesstimme' => '1',
                'Beitritt' => 1501,
                'Hauptort' => 'Schaffhausen',
                'Einwohner' => '77139',
                'Auslaender' => '24,2 %',
                'Flaeche' => '298',
                'Dichte' => '259',
                'Gemeinden' => 27,
                'Amtssprache' => 'deutsch',
            ),
        14 =>
            array (
                'Kuerzel' => 'AR',
                'Kanton' => 'Appenzell Ausserrhoden',
                'Standesstimme' => '0,5',
                'Beitritt' => 1513,
                'Hauptort' => 'Herisau, Trogen5',
                'Einwohner' => '53313',
                'Auslaender' => '14,5 %',
                'Flaeche' => '243',
                'Dichte' => '219',
                'Gemeinden' => 20,
                'Amtssprache' => 'deutsch',
            ),
        15 =>
            array (
                'Kuerzel' => 'AI',
                'Kanton' => 'Appenzell Innerrhoden',
                'Standesstimme' => '0,5',
                'Beitritt' => 1513,
                'Hauptort' => 'Appenzell',
                'Einwohner' => '15789',
                'Auslaender' => '9,9 %',
                'Flaeche' => '173',
                'Dichte' => '91',
                'Gemeinden' => 6,
                'Amtssprache' => 'deutsch',
            ),
        16 =>
            array (
                'Kuerzel' => 'SG',
                'Kanton' => 'St. Gallen',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'St. Gallen',
                'Einwohner' => '483156',
                'Auslaender' => '22,6 %',
                'Flaeche' => '2026',
                'Dichte' => '239',
                'Gemeinden' => 85,
                'Amtssprache' => 'deutsch',
            ),
        17 =>
            array (
                'Kuerzel' => 'GR',
                'Kanton' => 'Graubünden',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'Chur',
                'Einwohner' => '193388',
                'Auslaender' => '17,1 %',
                'Flaeche' => '7105',
                'Dichte' => '27',
                'Gemeinden' => 176,
                'Amtssprache' => 'deutsch, rätoromanisch, italienisch',
            ),
        18 =>
            array (
                'Kuerzel' => 'AG',
                'Kanton' => 'Aargau',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'Aarau',
                'Einwohner' => '627893',
                'Auslaender' => '22,9 %',
                'Flaeche' => '1404',
                'Dichte' => '440',
                'Gemeinden' => 219,
                'Amtssprache' => 'deutsch',
            ),
        19 =>
            array (
                'Kuerzel' => 'TG',
                'Kanton' => 'Thurgau',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'Frauenfeld',
                'Einwohner' => '251973',
                'Auslaender' => '23,0 %',
                'Flaeche' => '991',
                'Dichte' => '254',
                'Gemeinden' => 80,
                'Amtssprache' => 'deutsch',
            ),
        20 =>
            array (
                'Kuerzel' => 'TI',
                'Kanton' => 'Tessin',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'Bellinzona',
                'Einwohner' => '336943',
                'Auslaender' => '27,3 %',
                'Flaeche' => '2812',
                'Dichte' => '120',
                'Gemeinden' => 147,
                'Amtssprache' => 'italienisch',
            ),
        21 =>
            array (
                'Kuerzel' => 'VD',
                'Kanton' => 'Waadt',
                'Standesstimme' => '1',
                'Beitritt' => 1803,
                'Hauptort' => 'Lausanne',
                'Einwohner' => '729971',
                'Auslaender' => '32,2 %',
                'Flaeche' => '3212',
                'Dichte' => '226',
                'Gemeinden' => 326,
                'Amtssprache' => 'französisch',
            ),
        22 =>
            array (
                'Kuerzel' => 'VS',
                'Kanton' => 'Wallis',
                'Standesstimme' => '1',
                'Beitritt' => 1815,
                'Hauptort' => 'Sitten',
                'Einwohner 1' => '317022',
                'Auslaender 2' => '22,0 %',
                'Flaeche 3' => '5224',
                'Dichte 4' => '61',
                'Gemeinden 6' => 141,
                'Amtssprache' => 'französisch, deutsch',
            ),
        23 =>
            array (
                'Kuerzel' => 'NE',
                'Kanton' => 'Neuenburg ',
                'Standesstimme' => '1',
                'Beitritt' => 1815,
                'Hauptort' => 'Neuenburg',
                'Einwohner' => '173183',
                'Auslaender' => '24,4 %',
                'Flaeche' => '803',
                'Dichte' => '216',
                'Gemeinden' => 53,
                'Amtssprache' => 'französisch',
            ),
        24 =>
            array (
                'Kuerzel' => 'GE',
                'Kanton' => 'Genf',
                'Standesstimme' => '1',
                'Beitritt' => 1815,
                'Hauptort' => 'Genf',
                'Einwohner' => '473941',
                'Auslaender' => '37,0 %',
                'Flaeche' => '282',
                'Dichte' => '1633',
                'Gemeinden' => 45,
                'Amtssprache' => 'französisch',
            ),
        25 =>
            array (
                'Kuerzel' => 'JU',
                'Kanton' => 'Jura ',
                'Standesstimme' => '1',
                'Beitritt' => 1979,
                'Hauptort' => 'Delsberg',
                'Einwohner' => '70542',
                'Auslaender' => '13,0 %',
                'Flaeche' => '838',
                'Dichte' => '84',
                'Gemeinden' => 64,
                'Amtssprache' => 'französisch',
            ),
    );
}